/**
 * E2E Test Helpers
 *
 * Central export point for all test helper modules.
 */

// Condition functions
export {
  and,
  bankedAnimalsAbove,
  bankedAnimalsAtLeast,
  CONDITIONS,
  type ConditionFn,
  canBank,
  cannotBank,
  comboAbove,
  comboAtLeast,
  comboEqual,
  fallingAnimalsAtLeast,
  type GameSnapshot,
  hasBushes,
  hasDoublePoints,
  hasFallingAnimals,
  hasFallingAnimalType,
  hasFallingPowerUps,
  hasMagnet,
  hasSpecialAnimal,
  isGameOver,
  isInvincible,
  isNotInvincible,
  isNotPlaying,
  isPaused,
  isPlaying,
  levelAbove,
  levelAtLeast,
  livesAbove,
  livesBelow,
  livesEqual,
  noBushes,
  noFallingAnimals,
  noFallingPowerUps,
  not,
  or,
  playerInRange,
  playerNear,
  scoreAbove,
  scoreAtLeast,
  stackHeightAbove,
  stackHeightAtLeast,
  stackHeightEqual,
  wobbleAbove,
  wobbleWarning,
} from "./conditions";

// Game helpers
export {
  bankStack,
  type CanvasEvent,
  type CanvasEventType,
  clearGameStorage,
  clickBank,
  clickPause,
  clickResume,
  dispatchCanvasEvent,
  dragOnCanvas,
  getSnapshot,
  getStorageValue,
  type KeyboardEventConfig,
  movePlayerTo,
  STORAGE_KEYS,
  setStorageValue,
  setupErrorMonitoring,
  skipSplash,
  startGame,
  startGameAndWait,
  waitForCondition,
  waitForGameInstance,
  waitForGameOver,
  waitForPlaying,
  waitForScore,
} from "./game-helpers";
// Generator exports for property-based testing
export {
  // Constants
  ANIMAL_TYPES,
  CATCH_TOLERANCES,
  // Types
  type CanvasBounds,
  // Utility functions
  clamp,
  // Seeded random
  createSeededRandom,
  DEFAULT_CANVAS,
  DEFAULT_PLAYER,
  distance,
  // Animal/power-up generators
  generateAnimalType,
  generateAnimalTypes,
  // Position generators
  generateCatchZoneEdgeCases,
  generateCatchZonePositions,
  // Viewport generators
  generateCustomViewport,
  generateMissPositions,
  generatePlayerBoundaryEdgeCases,
  generatePlayerPositions,
  generatePositions,
  generatePowerUpType,
  generatePowerUpTypes,
  generateRandomViewport,
  // Test case generators
  generateSeeds,
  generateSpawnEdgeCases,
  generateSpawnPositions,
  generateTestCases,
  generateViewports,
  generateXPositions,
  generateYPositions,
  isWithinBounds,
  lerp,
  type PlayerConfig,
  POWER_UP_TYPES,
  type Position,
  type SeededRandom,
  type SpawnConfig,
  type TestPosition,
  VIEWPORTS,
  type ViewportConfig,
} from "./generators";
// Governor exports
export {
  DEFAULT_GOVERNOR_CONFIG,
  type GovernorConfig,
  type GovernorStats,
  getGovernorConfig,
  getGovernorStats,
  injectAndStartGovernor,
  injectGovernor,
  isGovernorRunning,
  resetGovernorStats,
  setGovernorConfig,
  startGovernor,
  stopGovernor,
  waitForBanks,
  waitForCatchAttempts,
  waitForGovernorFrames,
} from "./governor";
